version = 0.1

[default.deploy.parameters]
stack_name = "clinicalflow-ai"
resolve_s3 = true
s3_prefix = "clinicalflow-ai"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
